### ISSUE TITLE
Initialize the Project's frontend 

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#1]
Description:

S-1)  Initialize a React App:

S-2) Set up the frontend of the project using React.
Testing Libraries:

S-3) Integrate appropriate testing libraries, preferably Vite.
Code Quality and Style:

S-4) Configure ESLint for code linting.
Set up Tailwind CSS for styling.

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Manav-Khandurie** [comment]
Sure @Saga690  initilize the frontend in the **client** folder provided . Used React + Vite setup and add tailwind , eslint and prettier . 
Follow the OsoC'24 rules and regulations to ensure the PR adhere to it.
Good Luck.

**Comment by Saga690** [comment]
PR raised!
