### ISSUE TITLE
Create the S3 Media upload service

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#10]
S-1)  Build the Microservice to efficiently upload the files to an S3 bucket using Node Express

S-2) Ensure that we can have proper retrieval of item using API

S-3) Containerize the microservice

**Comment by adx04** [comment]
Hello Manav! i would like to work on this issue.

**Comment by Manav-Khandurie** [comment]
Sure @adx04  we are following the microservices arch so goto server folder , init you would be creating a brand new folder called `Storage-DB-Controller-Service` and initilize a brand new node project in the folder created.
Ensure usage of appropriate env variables for s3 creds . 
Also create a `.env.example` file where you will specify the env variables.

Any querries or suggestions would be discussed at discord or github only.
Good luck with the issue.
