### ISSUE TITLE
Frontend Auth Service Login and Signup

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#11]
Develop the functionality to have There will be client side authentication and authorization of users where the users should be able to come in they would be able to login with their credentials it can either be a login with Google or login via custom user password. There must be appropriate measures to ensure that the session is managed and that the users login is saved for future sessions also there needs to be mechanisms to log out users after some time

You must implement appropriate methods to detect unauthorised access and log out any session that is unauthorised or has been expired.

**Comment by rampantvoid** [comment]
Can you please assign this to me

**Comment by Manav-Khandurie** [comment]
> Can you please assign this to me

If you still interested , this is a frontend issue  now , just ping me .

**Comment by rampantvoid** [comment]
@Manav-Khandurie yeah i'm still interested in doing this

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie yeah i'm still interested in doing this

ok im assigning you this issue then @rampantvoid  ,
Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by adx04** [comment]
@Manav-Khandurie i would like to definitely work on this issue
is the frontend only required now?
and like in what theme and color choice should be there...should i make it in a dark theme
and should i initiate a react project?

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie i would like to definitely work on this issue
> is the frontend only required now?
> and like in what theme and color choice should be there...should i make it in a dark theme
> and should i initiate a react project?

yea @adx04 ,
This is a front-end issue where you will be integrating the client-side firebase with our react app so like you will provide functionalities like sign in with Google and sign in with github on the front end of the actual react app and then you will also be generating token IDs. Token IDs will be used to authenticate and authorize with the back-end. So the firebase after logging in and authenticating with the firebase, a token ID, is generated, which will be sent to the back-end server, and that back-end server would go forward and authenticate with the firebase So this issue in which we have to work with the front-end side of the firebase here you need to have you here you need to build the login page the sign up page where you will provide the option for a custom login using a custom email and password and a sign in with Google. After that, when the sign-in is done, you will be generating the firebase access token, which will be generated using the firebase SDK on the front-end, and that will be sent to the back-end, that's it. 
Ui is your choice

**Comment by adx04** [comment]
> This is a front-end issue where you will be integrating the client-side firebase with our react app so like you will provide functionalities like sign in with Google and sign in with github on the front end of the actual react app and then you will also be generating token IDs. Token IDs will be used to authenticate and authorize with the back-end. So the firebase after logging in and authenticating with the firebase, a token ID, is generated, which will be sent to the back-end server, and that back-end server would go forward and authenticate with the firebase So this issue in which we have to work with the front-end side of the firebase here you need to have you here you need to build the login page the sign up page where you will provide the option for a custom login using a custom email and password and a sign in with Google. After that, when the sign-in is done, you will be generating the firebase access token, which will be generated using the firebase SDK on the front-end, and that will be sent to the back-end, that's it.
> Ui is your choice

ok @Manav-Khandurie !

**Comment by adx04** [comment]
hello!@Manav-Khandurie 
i have created the react app with login/signup that leads to a basic profile page that also has the functionality to logout as well
along with Firebase token Id generation and session mgmt. ...i have also included the "react-toastify" to noftify toast messages as a popup whenever the user is loggin in/signing up whether he is logged in successfully or not .

**Comment by adx04** [comment]
where should i put my react app folder in?

**Comment by rampantvoid** [comment]
@Manav-Khandurie have handled client side auth with firebase and have used zod for validation checks and have also made api util

**Comment by rampantvoid** [comment]
have raised a pr

**Comment by adx04** [comment]
i have raised the PR !
these are the ss of the UI oof signin/signup
is this fine or should i make further changes?

![image](https://github.com/upes-open/OSoc-24-The-Content-Forge/assets/122734846/09a2c67a-295a-4f49-b1e2-6ee9f32a0862)

![image-1](https://github.com/upes-open/OSoc-24-The-Content-Forge/assets/122734846/387f4cf2-ff2f-4d11-b750-e825f831ffba)

![image-2](https://github.com/upes-open/OSoc-24-The-Content-Forge/assets/122734846/108a37a7-5d95-4d2e-bb00-da7dcdd35f77)
