### ISSUE TITLE
Build The Landing Page UI on Figma

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#14]
Create the landing page UI following the design guidelines in Figma.
Feel free to be creative and get it reviewed by  the project lead .
The Figma file access would also be provided by the Project Lead.

Note : -- UI type issues must be mentioned in the DesignChange.log file with appropriate Images with the PR

**Comment by Lavanya-glitch** [comment]
can i be assigned to this

**Comment by Manav-Khandurie** [comment]
> can i be assigned to this

Sure @Lavanya-glitch  , for this issue you you You would be creating a landing page for the app on figma ,
Will provide you with the figma design link .
Please share your email here for the edit access 

Figma file : [https://www.figma.com/design/YPy9AeWjCTJv3gw1DuzL8w/TheContentHub?node-id=0-1&t=soIh9BV94cu8PqSO-1](https://www.figma.com/design/YPy9AeWjCTJv3gw1DuzL8w/TheContentHub?node-id=0-1&t=soIh9BV94cu8PqSO-1)

**NOTE** :--
Please note that this is just a starting point a template you are free to edit it to your hearts content just ensure that you follow best design practices and build a clean ui any kind of resources like logo will be provided if present on discord itself.
Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Additionally you'll be editing the file `design\DESIGNLOG.md`  and attaching related screenshots for it to be properly considered as a contribution. Simply add your changes and mention the different things that were done.

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by Manav-Khandurie** [comment]
![Logo](https://github.com/upes-open/OSoc-24-The-Content-Forge/assets/123000337/374482c1-bd1c-44d4-8eed-50b2f43b3eff)

@Lavanya-glitch  this is the logo we are goin for as of now , feel free to come up with your own if you want or discuss it on discord , we might raise a new issue for logo specifically if needs be .

The logo would also be on discord in the resources section of `The Content Forge` vertical

**Comment by Lavanya-glitch** [comment]
bansallavanya2005@gmail.com

**Comment by Manav-Khandurie** [comment]
> bansallavanya2005@gmail.com

Request sent . Please check.

**Comment by Lavanya-glitch** [comment]
yes, thankyou

**Comment by ParthDhavan04** [comment]
Can I work on this?

**Comment by Manav-Khandurie** [comment]
> Can I work on this?

Sure

**Comment by rampantvoid** [comment]
@Manav-Khandurie hey if its still available would like to work on this
