### ISSUE TITLE
Audio , Video And Image Pages Design Creation on Figma

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#15]
Design the pages for audio video and image these pages will have functionalities of upload as well as generating videos there should be appropriate design for downloading videos and viewing them on the browser ensure that there is design prototypes for both mobile as well as web versions of the application and that there is a consistent user interface across the three pages.
All the designs that are proposed should be reviewed by the project lead and the figma file for the same would be provided by the project lead.
Additionally also ensure that the design that is proposed is implementable by the front end team.

Note : -- UI type issues must be mentioned in the DesignChange.log file with appropriate Images with the PR

**Comment by ParthDhavan04** [comment]
Hi! I would like to work on this.

**Comment by Manav-Khandurie** [comment]
> Hi! I would like to work on this.

Sure @ParthDhavan04  , You can work on the following task but first please send your email so I can add you as an editor on the figma file from there I will guide you through what kind of designs we want essentially we want pages for a few of these services and you can have any ui ux design in your mind as you like just make sure the ui is clean enough and it is implementable on react

**Comment by ParthDhavan04** [comment]
Hi! @Manav-Khandurie . Here is my email @parthdhavan2004@gmail.com

**Comment by Manav-Khandurie** [comment]
> Hi! @Manav-Khandurie . Here is my email @[parthdhavan2004@gmail.com](mailto:parthdhavan2004@gmail.com)

given please check , Additionally, I just wanted to point out that the current Figma design is not complete and this is just like a skeleton design. You can start from scratch and again try to keep the UI clean and as close to implementation as possible.

**Comment by ParthDhavan04** [comment]
Yes, I have the access to the Figma link. Thank you @Manav-Khandurie .

**Comment by rampantvoid** [comment]
@Manav-Khandurie can you assign this issue to me

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie can you assign this issue to me

Done
