### ISSUE TITLE
Image Content Creation Micro-Service 

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#16]
Use the pythons fast api framework to build the image creation service this service has 2 objectives it will fetch the image based on prompt from the Apis and then it will use python libraries like Pillow to create Create images like [example1](https://cdn-fkmoj.nitrocdn.com/xvpOGZRTxJUhXKufpOYIruQcRqtvAAQX/assets/images/optimized/rev-4e1f421/media.briantracy.com/blog/wp-content/uploads/2024/01/23111415/Quote-2.png) , [example2](https://quotefancy.com/media/wallpaper/3840x2160/6360926-Maya-Angelou-Quote-Nothing-will-work-unless-you-do.jpg)

Note :- You are not expected to build images that are 1:1 with the provided examples instead think of these examples as a starting point and you are free to choose the different themes based on which these images can be created in different styles.

**Comment by adx04** [comment]
Hi @Manav-Khandurie i would like trying to work on this issue as well
(please guide me a little like what kind of requirements/specifications are necessary)

**Comment by Manav-Khandurie** [comment]
> Hi @Manav-Khandurie i would like trying to work on this issue as well (please guide me a little like what kind of requirements/specifications are necessary)

OK so look this is somewhat of a service that would be basically editing these images that will be provided so like you have been provided with an image and text and you are supposed to build a image that looks somewhat like the examples that are shown below no need to worry about creating something which is 1:1 with the examples provided in the above comment but it needs to be close enough and for this you will most likely be using python libraries so use the FASTAPI framework and again if express js has some solution you can explore that as well the choice for the framework for this particular feature on microservice is up to you entirely so essentially what you do need to do here is that you will be given an image and a text and you need to merge those 2 and create a brand new image and similar to the examples provided in the above comment so refer to that and refer to additional dogs there are libraries in python like pillow that do the image processing task . 
 

**Again the Choice of FrameWork is up to you , my recommendation would still be goin with python's fastapi or any other python framework** 

Additional clause some of the related issues that would have been benefited You for developing this feature are not present what you can do is that you can decrease the scope of the issue and simply work on generating these images through api request so , So when like request are being sent with an image and a text you basically merge them and send that image back.

If you're interested @adx04  ,in this one do let me know it is one of those issues that is more open ended.

**Comment by adx04** [comment]
thanks @Manav-Khandurie will work on that!
regards

**Comment by Manav-Khandurie** [comment]
Ok Assigned

**Comment by adx04** [comment]
@Manav-Khandurie sorry for the time taken as i have been involed with my internship as well
i have mentioned all the details in a Readme file
i have generated a service using PIL and Fast API ,where should i keep my microservice folder in the project?

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie sorry for the time taken as i have been involved with my internship as well
> i have mentioned all the details in a Readme file
> i have generated a service using PIL and Fast API ,where should i keep my microservice folder in the project?
> 

yea @adx04 , the folder in which you have to add the service is `server\image-creation-service`

**Comment by adx04** [comment]
> > @Manav-Khandurie sorry for the time taken as i have been involved with my internship as well
> > i have mentioned all the details in a Readme file
> > i have generated a service using PIL and Fast API ,where should i keep my microservice folder in the project?
> 
> yea @adx04 , the folder in which you have to add the service is `server\image-creation-service`

ok @Manav-Khandurie
