### ISSUE TITLE
Video Creation Microservice with automated animated subs.

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#18]
Create the video creation microservice that will take Videos from the Apis and then it will create appropriate videos using the previously created subtitles services and whisper services and basically combine them into a short form video kind of like this so the user would be able to upload the video in the back end the service would be able to extract the audio generate the subtitles and then attach the subtitles to the already present video and after that the new video would have options of creation of different types of subtitles which is common for short form video content some of the examples are provided below [Example1](https://youtube.com/shorts/eWT-6a8Xnos?si=f5RdE2NnqIdjPdJw) , [example2](https://youtube.com/shorts/4lEqmJwFFYg?si=1RG6DjNm-SiLFiYw).

Note :-- You don't have to create videos that are one is to one with the example videos instead take this example videos as kind of like a blueprint that you can use to build this video creation service that will also be using the subtitle service that was created before for this service the videos that are created would inevitably be stored in the S3 bucket .

Please make sure that the videos that are generated meet the quality standards. 
You are free to utilise different python libraries to achieve the task and try to do this task within the confines of the fast api framework.

**Comment by rampantvoid** [comment]
@Manav-Khandurie can you assign this to me

**Comment by Manav-Khandurie** [comment]
Ok @rampantvoid  , follow the above steps
