### ISSUE TITLE
Setup Backend Environment

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#2]
S-1) Setup the Basic Structure of the backend app

S-2) Initialize different folders for different Microservices

S-3) Create Sample placeholder dockerfiles and docker-compose files

Make Sure we have appropriate tools setup at the backend to properly work 
Use tools like ESLint & Prettier for code quality ,

**Comment by rampantvoid** [comment]
Hi can you assign this issue to me

**Comment by Manav-Khandurie** [comment]
> Hi can you assign this issue to me

Sure @rampantvoid  ,So remember that this is a microservices based project where the back end is divided into several different microservices each of those microservices will be working with different framework or tech stack , so  for this issue in particular you will be setting up the back end and essentially the setting up the back end directory structure so that future contributors can easily manage the directories For these microservices.

So in the folder `server` 

You will be creating 9 separate directories  and add a empty `.gitkeep` file & `DOCKERFILE` file in every single one of them 

here is the naming convention please follow it throughly

Folder 1 : `auth-service`
Folder 2 : `controller-service`
Folder 3 : `image-creation-service`
Folder 4 : `image-video-generation-service`
Folder 5 : `ffmpeg-service`
Folder 6 : `whisper-service`
Folder 7 : `sst-service`
Folder 8 : `tts-service`
Folder 9 : `storage-controller-service`

Note : - Ensure that each one of these folders are present under the parent folder `server` And at each one of these folders have an empty `.gitkeep` file  & `DOCKERFILE`

Additionally add a `BACKENDLOG.md`  & `docker-compose.yml` file at `server/` with the file contents as follows
