### ISSUE TITLE
Build the Auth Microservice 

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#3]
S-1) In the backend folder , start working on the Auth service Microservice

S-2) Integrate Firebase Authentication , Authorization , Signup , Sign in 

S-3) Create the Service , Test it and Integrate with Frontend with appropriate API Endpoints

FireBase Creds required will be provided

**Comment by rampantvoid** [comment]
can you assign this issue to me?

**Comment by Manav-Khandurie** [comment]
> can you assign this issue to me?

Sure @rampantvoid  ,you'll be working in `server/auth-service` folder ,Initialised the project with a node express backend  
For this issue you will be required to create an authentication service that will be communicating with a fire based project and what will happen is that it will be able to authenticate users and any invalid users will simply be rejected so you need to create appropriate api endpoints that will be able to deal with the authentication with firebase component of the application this is the backed component to the front end counterpart

Use appropriate firebase libraries for node for this task
Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by sakshammaggu** [comment]
@Manav-Khandurie hi, i would like to take up this issue, pls assign me. Also where i can find the firebase creds and also state the endpoints too.

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie hi, i would like to take up this issue, pls assign me. Also where i can find the firebase creds and also state the endpoints too.

Firebase creds are at Discord server , Under resources 
Ok you are assigned but as someone is alredy working on it whichever person completes first gets the points .

Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by sakshammaggu** [comment]
@Manav-Khandurie I am not able to see the creds on resources tab

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie I am not able to see the creds on resources tab, pls help me with it

No worries @sakshammaggu  ,send your mail I would send the creds 
Additional raise the same issue in discord osoc doubts section as well

**Comment by sakshammaggu** [comment]
@Manav-Khandurie  email: sakshammaggu80@gmail.com  . Yeah raised the issue on discord

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie  email: sakshammaggu80@gmail.com  . Yeah raised the issue on discord

Sent 
Please confirm

**Comment by sakshammaggu** [comment]
@Manav-Khandurie Yeah got the creds. Also some imp extra info regarding Auth service if you want to mention , it would be great.

**Comment by rampantvoid** [comment]
@Manav-Khandurie have implemented auth service, used ts, have made 2 middlewares, authentication and authorization, handling email&pass register and oauth register, updating 'user claims' on the firebase idToken and forcing a refresh, so login can be handled entirely on the client side with firebase, the new idToken have a claim called 'role':'user', which is accessed by authorization middleware to handle access control

**Comment by rampantvoid** [comment]
have raised a pr
