### ISSUE TITLE
Whisper service for Audio processing and Subtitle generation

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#4]
Use FastAPI to create a microservice that communicates with the openai's Whipser model to do audio processing and extract audio in subtitle files 

The model used would be available at [Whipser Repo](https://github.com/openai/whisper.git)

Read the documentation and build the entire Microservice , with appropriate Dockerfiles and API endpoint to host and utilize the service

Additionally store the Audio files in a s3 bucket , Creds will be provided by the lead.

**Comment by Siddharthaaa21** [comment]
made a model like, can use s3 bucket as well as the with fastapi 
since didnt had s3 bucket credentials.
shall i?

**Comment by Manav-Khandurie** [comment]
> made a model like, can use s3 bucket as well as the with fastapi since didnt had s3 bucket credentials. shall i?

We have a separate service that will handle working with s3 @Siddharthaaa21
