### ISSUE TITLE
Implement Video Upload Component

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#6]
Develop a React component that allows users to upload video files. Ensure it supports drag-and-drop functionality and displays a progress bar during the upload process.

Contact the project Lead for any Design and implementation related issues .

**Comment by nandiniiiiiiii** [comment]
please assign this to me.

**Comment by Manav-Khandurie** [comment]
> please assign this to me.

Sure @nandiniiiiiiii  . Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by nandiniiiiiiii** [comment]
is there any particular interface that needs to be applied or should I just simply apply it on the main component.

**Comment by Manav-Khandurie** [comment]
> is there any particular interface that needs to be applied or should I just simply apply it on the main component.

No @nandiniiiiiiii  , right now cause the `ui/ux` issues are not done there is no interface so you can apply any basic interface you want.

**Comment by Manav-Khandurie** [comment]
Completed
