### ISSUE TITLE
Create Audio Upload Component

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#7]
Develop a React component for users to upload audio files. The component should include drag-and-drop support and a progress indicator.

The appropriate UI design would be created after the UI issues are resolved .

**Comment by adx04** [comment]
hi Manav! i would also like to work on this issue
(pls mention the requirements or tech stack as well)

**Comment by Manav-Khandurie** [comment]
> hi Manav! i would also like to work on this issue (pls mention the requirements or tech stack as well)

Sure @adx04  , In this issue we'll be creating a audio component which will basically deal with the uploading of the audio files and then processing those audio files respectively so the user would come he will upload the audio files , files should be processed by the back end and after the processing of the back end the front end would be able to have play options with the audio file so the user should be able to start stock these audio files that would be played on the front end and it should also provide an option to download these files if needs be.

Because we have not set up the back end yet you can simply mock the back end and basically you need to build an audio upload and processing service component on the front end that will be dealing with audio playback controls downloads as well as uploads

The choice of ui is up to you because we have not yet finalized the ui just keep it in such a way that it's extendable

**NOTE** : -You will be working in the `client` folder   which is a react + vite setup .

Please follow all the guidelines and ensure that the p r raised Is following all the rules and regulation of OsoC'24 .

Use discord or github to clarify any doubts regarding the issue.
Good luck 👍

**Comment by adx04** [comment]
@Manav-Khandurie should i make changes directly in the files provided in client folder or for now just create a separate folder for the audio component in the folder?

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie should i make changes directly in the files provided in client folder or for now just create a separate folder for the audio component in the folder?

Directly in the `client` folder itself no need for a brand new folder in `client`
