### ISSUE TITLE
Integrate FFmpeg via WebAssembly for Video Processing

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#8]
Integrate FFmpeg compiled to WebAssembly into the React application to handle client-side video processing tasks such as format conversion and compression.

Ensure utilization of different tools for compression of audio video or image files for efficient front and back end communication use front end libraries like Web Assembly to achieve this functionality.

**Comment by adx04** [comment]
@Manav-Khandurie i would like to try working on this issue!
guide me a little like in which files should i make changes or should i initialise a new react project
and what should it look like and what should be the tech stack and functionalities

**Comment by Manav-Khandurie** [comment]
> @Manav-Khandurie i would like to try working on this issue! guide me a little like in which files should i make changes or should i initialise a new react project and what should it look like and what should be the tech stack and functionalities

Okay @adx04  so in this issue you'll be working on the front end of the application in the `client` folder where you would be adding the functionality of converting video into its different formats for download purchases so the front end would provide the capability of downloading the video in a different format which is done on the client side not on the server side to reduce the load on the server side so for example if we get a video in the format of MP4 from the server the front end should be capable enough to convert that mp4 format to another format like mkv, This is often achieved by libraries like ffmpeg for react . 

This feature would allow users to download videos in different formats and would also reduce the load on the back end servers

**Comment by adx04** [comment]
ok! @Manav-Khandurie will surely work on the same!

**Comment by rampantvoid** [comment]
@Manav-Khandurie hi can you assign this issue to me

**Comment by adx04** [comment]
have raised the pr @Manav-Khandurie  for this issue !
