### ISSUE TITLE
S3- Frontend Audio Files Conversion Functionality 

### ISSUE THREAD

**Issue by Manav-Khandurie** [upes-open/OSoc-24-The-Content-Forge#9]
Develop functionality to fetch files from an S3 bucket and convert them on the front end using FFmpeg compiled to WebAssembly. This will enable users to change audio quality or video format directly in their browser.

**Comment by Aditya-567** [comment]
i would like to take this issue

**Comment by Manav-Khandurie** [comment]
Sure @Aditya-567  , Use Node Express and FFMPEG

**Comment by rampantvoid** [comment]
@Manav-Khandurie hi can you assign this to me

**Comment by rampantvoid** [comment]
@Manav-Khandurie if it's still available i would like to work on it

**Comment by Manav-Khandurie** [comment]
Sure @rampantvoid
